# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'ObjcDemo' do
    pod 'LYTSDK',   '~> 1.0.06'
    pod 'HPWVisitorSDK','~> 3.1.5'
end
